### ISSUE TITLE
You are expecting 0-11 for the Month field, when it should be 1-12

### ISSUE THREAD

**Issue by chrisroos** [technoweenie/cronwtf#1]
Currently, this (0 0 0 1 0 COMMAND) is parsed as "Runs `COMMAND` at minute :00, on hour 0, on day 0, in Feb, on Sun.", when it should actually be parsed as "Runs `COMMAND` at minute :00, on hour 0, on day 0, in Jan, on Sun." (NOTE the change from Feb to Jan).

This is documented in the wikipedia entry (http://en.wikipedia.org/wiki/Cron) and I've just confirmed by testing (I have a one off task that I need to run tonight) on a linux install.

**Comment by sunny** [comment]
Fixed with #2

**Comment by alexmglover** [comment]
It seems like this is still an issue.  Entering 1 tells me that the month is February.

**Comment by navarr** [comment]
Oh, it is.  #2 is a Pull Request to fix #1.  It's just never been pulled.
